config/routes.rb
Rails.application.routes.draw do
  resources :subscribers

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  get 'u/:id/', to: 'users#dashboard', as: 'user'

  get 'my-posts', to: 'posts#my_posts'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/subscriber.rb
# app/models/subscriber.rb
class Subscriber < ApplicationRecord
    validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end
  

app/controllers/subscribers_controller.rb
# app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController

  def index
    @subscribers = Subscriber.all
  end

  def create
    @subscriber = Subscriber.new(subscriber_params)
    if @subscriber.save
      flash[:notice] = 'You are added as a subscriber! Congratulations'
    else
      flash[:alert] = 'Failed to subscribe. Please try again.'
    end
    redirect_to root_path
  end

  def destroy
    @subscriber = Subscriber.find(params[:id])
    @subscriber.destroy
    redirect_to subscribers_url, notice: 'Subscriber was successfully deleted.'
  end

  private

  def set_posts
    @posts = Post.all.limit(3).order('created_at DESC')
  end

  def subscriber_params
    params.require(:subscriber).permit(:email)
  end
  
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/create.html.erb
<h1>Subscribers#create</h1>
<p>Find me in app/views/subscribers/create.html.erb</p>

app/views/subscribers/index.html.erb
<div class="container mt-5 mb-5">
  <div class="card shadow">
    <div class="card-body">
      <h1 class="card-title">Subscribers</h1>
      <table class="table table-striped">
        <thead class="thead-dark">
          <tr>
            <th>Email</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @subscribers.each do |subscriber| %>
            <tr>
              <td><%= subscriber.email %></td>
              <td>
                <%= button_to "Delete", subscriber_path(subscriber), method: :delete, class: "btn btn-danger btn-sm" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/subscribers/unsubscribe.html.erb
<h1>Subscribers#unsubscribe</h1>
<p>Find me in app/views/subscribers/unsubscribe.html.erb</p>