config/routes.rb
Rails.application.routes.draw do
  resources :subscribers

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  get 'u/:id/', to: 'users#dashboard', as: 'user'

  get 'my-posts', to: 'posts#my_posts'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/post.rb
class Post < ApplicationRecord
    serialize :keywords, Array, coder: JSON
    belongs_to :user

    has_one_attached :image
    has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  def my_posts
    @my_posts = current_user.posts
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments.order('created_at DESC')
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.keywords = params[:post][:keywords].split(',').map(&:strip)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id, :image, keywords: [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :content, class: "form-label" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :keywords, class: "form-label" %>
    <%= form.text_area :keywords, value: @post.keywords.join(', '), placeholder: 'Enter keywords separated by commas', class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :image, class: "form-label" %>
    <%= form.file_field :image, class: "form-control" %>
  </div>
  <div>
    <%= form.text_field :user_id, type: "hidden" %>
  </div>
  <div class="mt-3">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <%= post.title %>
  </p>
  <p>
    <%= post.content %>
  </p>
  <p>
    <%= post.keywords %>
  </p>
</div>

app/views/posts/edit.html.erb
<div class="container mt-5 mb-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow-sm rounded">
        <div class="card-body">
          <h1 class="card-title">Editing post</h1>
          <%= render "form", post: @post %>
          <br>
          <div class="mt-3">
            <%= link_to "Show this post", @post, class: "btn btn-primary me-2" %>
            <%= link_to "Back to posts", posts_path, class: "btn btn-secondary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<style>
  .post-card {
    margin-bottom: 20px;
    position: relative; /* Enable positioning */
    border-radius: 20px; /* Same radius as the container */
  }

  .post-card .card-title {
    font-size: 1.5rem;
  }

  .post-card .card-text {
    color: #555;
  }

  .post-card a.btn {
    color: #fff;
    background-color: #007bff; /* Blue */
    border-color: #007bff;
  }

  .post-card a.btn:hover {
    background-color: #0056b3; /* Darker Blue */
    border-color: #0056b3;
  }

  .keyword-box {
    background-color: #f1f1f1; /* Light Gray */
    color: #555;
    padding: 5px 10px;
    font-size: 0.8rem;
    border-radius: 5px;
    left: 10px; /* Distance from left */
    margin-top: 20px; /* Margin top */
    width: fit-content;
  }
</style>
<main>
  <h1 class="text-center mt-4">All Posts</h1>
  <div class="container mt-4 mb-4">
    <% if @posts.any? %>
      <div class="row">
        <% @posts.each do |post| %>
          <div class="col-md-4">
            <div class="post-card shadow">
              <div class="card p-2">
                <!-- Add image here -->
                <%= image_tag post.image, class: "card-img-top", alt: "Featured Post Image", style: "height: 300px; object-fit: cover;" %>
                <div class="card-body p-0 pt-2">
                  <h5 class="card-title"><%= post.title %></h5>
                  <p class="card-text"><%= truncate(post.content, length: 50) %></p>
                  <%= link_to "Show this post", post, class: "btn btn-primary" %>
                  <div class="d-flex flex-row gap-2">
                    <% post.keywords.each do |keyword| %>
                      <div class="keyword-box">
                        <%= keyword %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <p>No posts for now!</p>
    <% end %>
  </div>
</main>

app/views/posts/my_posts.html.erb
<style>
  .post-card {
    margin-bottom: 20px;
    position: relative; /* Enable positioning */
    border-radius: 20px; /* Same radius as the container */
  }

  .post-card .card-title {
    font-size: 1.5rem;
  }

  .post-card .card-text {
    color: #555;
  }

  .post-card a.btn {
    color: #fff;
    background-color: #007bff; /* Blue */
    border-color: #007bff;
  }

  .post-card a.btn:hover {
    background-color: #0056b3; /* Darker Blue */
    border-color: #0056b3;
  }

  .keyword-box {
    background-color: #f1f1f1; /* Light Gray */
    color: #555;
    padding: 5px 10px;
    font-size: 0.8rem;
    border-radius: 5px;
    left: 10px; /* Distance from left */
    margin-top: 20px; /* Margin top */
    width: fit-content;
  }
</style>
<main>
  <h1 class="text-center mt-4">My Posts</h1>
  <div class="container mt-4 mb-4">
    <% if @my_posts.any? %>
      <div class="row">
        <% @my_posts.each do |post| %>
          <div class="col-md-4">
            <div class="post-card shadow">
              <div class="card p-2">
                <!-- Add image here -->
                <%= image_tag post.image, class: "card-img-top", alt: "Featured Post Image", style: "height: 300px; object-fit: cover;" %>
                <div class="card-body p-0 pt-2">
                  <h5 class="card-title"><%= post.title %></h5>
                  <p class="card-text"><%= truncate(post.content, length: 50) %></p>
                  <%= link_to "Show this post", post, class: "btn btn-primary" %>
                  <div class="d-flex flex-row gap-2">
                    <% post.keywords.each do |keyword| %>
                      <div class="keyword-box">
                        <%= keyword %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <p>No posts for now!</p>
    <% end %>
  </div>
</main>

app/views/posts/new.html.erb
<div class="container mt-5 mb-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card shadow rounded">
        <div class="card-body">
          <h1 class="card-title">New Post</h1>
          <%= render "form", post: @post %>
          <div class="mt-3">
            <%= link_to "Back to posts", posts_path, class: "btn btn-secondary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<style>
  .hero-section {
    background-image: url('<%= url_for(@post.image) %>'); /* Dummy image */
    background-size: cover;
    background-position: center;
    color: #fff;
    text-align: center;
    padding: 100px 0;
    position: relative;
  }

  .hero-section:after {
    content: "";
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    position: absolute;
    background-color: rgba(0, 0, 0, 0.5);
  }

  .hero-title {
    font-size: 3rem;
  }
</style>
<div class="hero-section">
  <div class="container z-2 position-relative">
    <h1 class="hero-title"><%= @post.title %></h1>
    <div class="row">
      <% if current_user && current_user.id == @post.user_id %>
        <div class="col-md-6 offset-md-3 d-flex align-items-center justify-content-center gap-2">
          <%= link_to "Edit", edit_post_path(@post), class: "btn btn-primary btn-lg" %>
          <%= button_to "Delete", post_path(@post), method: :delete, class: "btn btn-danger btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="container mt-5 mb-5">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <!-- Post content here -->
      <p><%= @post.content %></p>
    </div>
  </div>
</div>
<%# Rendering Comments %>
<div class="py-4">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card shadow-sm rounded">
          <div class="card-body">
            <%= render 'comments/form', post: @post %>
          </div>
        </div>
      </div>
    </div>
    <div class="row justify-content-center mt-4">
      <div class="col-md-8">
        <% @comments.each do |comment| %>
          <div class="card shadow-sm rounded mb-3">
            <div class="card-body">
              <%= render 'comments/comment', post: @post, comment: comment %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>