config/routes.rb
Rails.application.routes.draw do
  resources :subscribers

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  get 'u/:id/', to: 'users#dashboard', as: 'user'

  get 'my-posts', to: 'posts#my_posts'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"
end

app/views/layouts/_footer.html.erb
<% if user_signed_in? %>
  <!-- Footer Section -->
  <footer class="footer">
    <div class="container">
      <div class="footer-links text-center">
        <ul>
          <li><a href="#">Home</a></li>
          <li><a href="#">About Us</a></li>
          <li><a href="#">Blog</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
      </div>
    </div>
  </footer>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "The Post", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Posts", posts_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Posts", my_posts_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if user_signed_in? && current_user.avatar_url.present? %>
              <%= image_tag(current_user.avatar_url, class: "avatar img-thumbnail rounded-circle me-1", style: "width: 40px") %>
              <%= current_user.name %>
            <% elsif user_signed_in? && !current_user.avatar_url.present? %>
              <%= current_user.name %>
            <% else %>
              Actions
            <% end %>
          </a>
          <ul class="dropdown-menu dropdown-menu-end">
            <%= render 'user/session_manager' %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%# Custom Tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <!-- Place this in the head of your HTML layout -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <style>
      body, html {
        margin: 0;
        padding: 0;
        height: 100%;
      }

      .message-container {
        position: fixed;
        top: 30px;
        left: 0;
        width: 100%;
        display: flex;
        justify-content: center;
        align-items: center;
        z-index: 9999;
      }

      .alert {
        position: relative;
        z-index: 9999;
      }

      .progress-bar-container {
        position: absolute;
        bottom: 0;
        left: 0;
        width: 100%;
        height: 8px; /* Height of the progress bar */
        background-color: transparent;
        overflow: hidden;
      }

      .progress-bar {
        height: 100%;
        border-radius: 4px; /* Half the height of the progress bar */
        background-color: #6c757d;
        animation: progressAnimation 5s linear forwards; /* Animation duration */
      }

      @keyframes progressAnimation {
        0% { width: 100%; } /* Start at full width */
        100% { width: 0%; } /* End at zero width */
      }
    </style>
  </head>
  <body>
    <header>
      <%= render 'layouts/navbar' unless @hide_nav == true %>
    </header>
    <main>
      <% if notice %>
        <div class="message-container">
          <div class="notice alert alert-success" role="alert">
            <%= notice %>
            <div class="progress-bar-container">
              <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>
        </div>
      <% elsif alert %>
        <div class="message-container">
          <div class="alert alert-danger" role="alert">
            <%= alert %>
            <div class="progress-bar-container">
              <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>
        </div>
      <% end %>
      <%= yield %>
      <script>
        document.addEventListener('DOMContentLoaded', function() {
          var messageContainers = document.querySelectorAll('.message-container');
          messageContainers.forEach(function(container) {
            setTimeout(function() {
              container.style.display = 'none';
            }, 5000); // Hide after 5 seconds
          });
        });

        // Force hide after 5 seconds
        setTimeout(function() {
          var messageContainers = document.querySelectorAll('.message-container');
          messageContainers.forEach(function(container) {
            container.style.display = 'none';
          });
        }, 5000);
      </script>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>